const EVENTS_AMOUNT = 20;
const TIME_PARSE_COEFFICIENT = 3600000;

const MONTHS = [`JAN`, `FEB`, `MAR`, `APR`, `MAY`, `JUN`, `JUL`, `AUG`, `SEP`, `OCT`, `NOV`, `DEC`];

export {EVENTS_AMOUNT, TIME_PARSE_COEFFICIENT, MONTHS};
